# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzImageLabelingDemo' do
  use_frameworks!

  pod 'Fritz', '~> 5.3.1'
  pod 'Fritz/VisionLabelModel/Fast'

end
