included:
  - Heartbeat/Source
excluded:
  - Pods
  - Supporting Files
opt_in_rules:
  - attributes
  - closure_end_indentation
  - empty_count
  - explicit_top_level_acl
  - force_unwrapping
disabled_rules:
  - explicit_top_level_acl
  - line_length
