# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzStyleTransferDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Fritz', '~> 5.3.7'
  pod 'Fritz/VisionStyleModel/Paintings'

end
