# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FritzObjectDetectionDemo' do
  use_frameworks!

  pod 'Fritz', '~> 5.3.7'
  pod 'Fritz/VisionObjectModel/Fast'

end
